services:
  - type: web
    name: portfolio-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: MONGODB_URI
        value: your-mongodb-uri
      - key: PORT
        value: 3001
