services:
  - type: web
    name: portfolio-backend
    env: node
    plan: free
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && node index.js"
    envVars:
      - key: MONGODB_URI
        value: your-mongodb-uri
      - key: PORT
        value: 3000
